name: m_flow
description: "Markdown Document Writer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  flutter_markdown: ^0.7.2+1
  html: ^0.15.4
  http: ^1.2.1
  markdown: ^7.2.2
  pdf: ^3.10.8
  screenshot: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - "assets/fonts/trim/trim.ttf"
    - "assets/fonts/RusticBlackShadow/RusticBlackShadow.ttf"
    - "assets/themes/github.json"