name: m_flow
description: "Markdown Document Writer."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  html: ^0.15.4
  http: ^1.2.1
  markdown: ^7.2.2
  pdf: ^3.10.8
  screenshot: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


assets:
  trim: "assets/fonts/trim/trim.ttf"
  rustic: "assets/fonts/RusticBlackShadow/RusticBlackShadow.ttf"
  githubTheme: "assets/themes/github.json"
